;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = lib/esp-iot-base/platformio.ini

[common]
build_flags =
    -std=c++2a
    -fconcepts
    ; ${iot.extra_release_flags}
    ; -Wall
    -DIOT_ENABLE_PERSISTENCE
    -DIOT_PERSISTENCE_EERAM_47L16
    -DIOT_ENABLE_SYSTEM_CLOCK
    -DIOT_SYSTEM_CLOCK_HW_RTC
    -DIOT_ENABLE_MQTT
    -DMQTT_MAX_PACKET_SIZE=2048
    ; -DDEBUG_ESP_PORT=Serial
    ; -DDEBUG_ESP_SSL
    ; -DDEBUG_ESP_HTTP_SERVER
    ; -DDEBUG_ESP_WIFI
    ; -DTEST_BUILD
    ; -DSIMPLE_I2C_DEBUG

build_unflags = -std=c++11 -std=gnu++17

[env:esp_local_debug]
platform = espressif8266@4.2.1
board = esp12e
framework = arduino
upload_speed = 460800
monitor_speed = 74880
monitor_filters = esp8266_exception_decoder, default
upload_resetmethod = nodemcu

build_flags =
    ${iot.build_flags}
    ${iot.release_flags}
    ${common.build_flags}
    -DTEST_BUILD

lib_deps =
    ${iot.lib_deps}

build_unflags =
    ${common.build_unflags}

[env:esp_deploy]
platform = espressif8266@4.2.1
board = esp12e
framework = arduino
upload_speed = 460800
monitor_speed = 74880
monitor_filters = esp8266_exception_decoder, default
upload_protocol = espota
upload_port = furnace.iot.home
upload_flags = --auth="${sysenv.PIO_ESP_THERMOSTAT_AUTH}"

build_flags =
    ${iot.build_flags}
    ${iot.release_flags}
    ${common.build_flags}

lib_deps =
    ${iot.lib_deps}

build_unflags =
    ${common.build_unflags}

[env:unit_test]
platform = native
test_framework = googletest
build_flags = ${common.build_flags}
build_unflags = ${common.build_unflags}